### ISSUE TITLE
How can I see the p value

### ISSUE THREAD

**Issue by ruan2ruan** [cdriveraus/ctsem#12]
data("ctExample1TIpred") 
tipredmodel <- ctModel(n.manifest = 2, n.latent = 2, n.TIpred = 1, 
                       manifestNames = c("LeisureTime", "Happiness"), 
                       latentNames = c("LeisureTime", "Happiness"), 
                       TIpredNames = "NumFriends", Tpoints = 6, LAMBDA = diag(2), 
                       TRAITVAR = "auto") 
tipredfit <- ctFit(dat = ctExample1TIpred, ctmodelobj = tipredmodel)
summary(tipredfit, verbose = TRUE)["addedTIPREDVAR"]

How can I see the p value in the output?

**Comment by cdriveraus** [comment]
Not sure what element you want a p-value for, you can use model comparison approaches outlined elsewhere in the manual, you can compute a p value using the std error shown in the summary, or possibly more appropriately use the ctCI function to get profile likelihood confidence intervals. Alternatively, the newer ctsem formulation is more robust and flexible and gives more of this sort of summary statistic, though still not a p-value, because there are just too many parameters where it is not clear what a p-value means.

```
tipredfit <- ctCI(tipredfit, 'TIeffect_Happiness_NumFriends')
summary(tipredfit)

#new formulation
timodel <- ctModel(
  type='stanct', #continuous time model via stan code
  tipredDefault = FALSE, #assume no ti pred effects unless specified
  manifestNames = c("LeisureTime", "Happiness"),
  latentNames = c("LeisureTime", "Happiness"),
  TIpredNames = "NumFriends", LAMBDA = diag(2),
  MANIFESTMEANS=c('LeisureInt||||NumFriends','HappinessInt||||NumFriends'), # | is used as a separator for different parameter elements
  T0MEANS=c('LeisureT0||||NumFriends','HappinessT0||||NumFriends') # the 5th element is used for tipred effects
)

newdat <- ctWideToLong(ctExample1TIpred,Tpoints = 6,n.manifest = 2,n.TDpred = 0,n.TIpred = 1,
  manifestNames = timodel$manifestNames,TIpredNames = timodel$TIpredNames)
newdat <- ctDeintervalise(datalong = newdat)

newfit <- ctStanFit(datalong = newdat,ctstanmodel = timodel)
summary(newfit)

```
