### ISSUE TITLE
32-bit builds of cstem fail on Launchpad

### ISSUE THREAD

**Issue by marutter** [cdriveraus/ctsem#7]
This is a minor issue, but the i386 (32-bit) builds fail on Launchpad for Ubuntu.  The amd64 (64-bit) build fine, which is very rare.  Here is the error:

make[1]: Entering directory '/<<PKGBUILDDIR>>/src'
"/usr/lib/R/bin/Rscript" -e "source(file.path('..', 'tools', 'make_cc.R')); make_cc(commandArgs(TRUE))" stan_files/ctsm.stan
Error in file(con, "r") : invalid 'description' argument
Calls: make_cc -> cat -> readLines -> file
Execution halted
Makevars:18: recipe for target 'stan_files/ctsm.cc' failed
make[1]: *** [stan_files/ctsm.cc] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>/src'
make[1]: Entering directory '/<<PKGBUILDDIR>>/src'
make[1]: Leaving directory '/<<PKGBUILDDIR>>/src'
ERROR: compilation failed for package ‘ctsem’

Full buildlog can be found here:
https://launchpadlibrarian.net/436747358/buildlog_ubuntu-bionic-i386.ctsem_3.0.0-1cran1ppabionic0_BUILDING.txt.gz

**Comment by cdriveraus** [comment]
Thanks. 32 bit is not a priority in general as it generally fails due to the large size of the stan models, some workarounds were implemented to get a semi functional form working on win32 for CRAN purposes, I might fix this at some point -- if anyone gives a convincing reason for 32 bit I'll fix it faster!
